import type { Metadata } from "next";
import { ThemeProvider } from "../providers/theme-provider";
import ClerkProvider from "../providers/clerk-provider";

import "./globals.css";
import "@unocss/reset/tailwind.css";
import { Header } from "./components";

export const metadata: Metadata = {
	title: "Clerk Take-Home",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased bg-background dark:bg-background font-questrial">
				<div className="flex flex-col w-full justify-items-center max-w-5xl mx-auto px-2">
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						themes={["light", "dark", "system"]}
						enableSystem
					>
						<ClerkProvider>
							<Header />
							<main className="min-w-full max-w-5xl">{children}</main>
						</ClerkProvider>
					</ThemeProvider>
				</div>
			</body>
		</html>
	);
}
